# Generated by Django 5.0.1 on 2024-02-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='client',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='product',
            new_name='medicine',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.CharField(default='Client', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
