# Generated by Django 5.0.1 on 2024-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_expiry_date_alter_userprofile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Supplements', 'Supplements'), ('Vitamins', 'Vitamins'), ('Diet and nutrition', 'Diet and nutrition'), ('Tea and coffee', 'Tea and coffee')], max_length=20, null=True),
        ),
    ]
