# Generated by Django 5.0.1 on 2024-02-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
