# Generated by Django 5.0.1 on 2024-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_reorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
