# Generated by Django 5.0.1 on 2024-02-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='completed', max_length=15, choices=(('completed', 'Completed'), ('cancelled', 'Cancelled'))
                                   ),)


    ]
