# Generated by Django 5.0.1 on 2024-02-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed'),
        ),
    ]
