# Generated by Django 5.0.1 on 2024-03-16 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='medicine',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='physical_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
