# Generated by Django 5.0.1 on 2024-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240219_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='medicine',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
