# Generated by Django 5.0.1 on 2024-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20240218_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=10),
        ),
    ]
