# Generated by Django 5.0.1 on 2024-03-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_order_invoice_no_alter_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
